version: '3.3'

services:
    
  mailhog:
    image: 'mailhog/mailhog'
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    container_name: mailhog


  adminer:
    image: 'ghcr.io/jeliebig/adminer-autologin'
    restart: always
    environment:
      - ADMINER_PLUGINS=login-env-vars
      - ADMINER_DRIVER=pgsql
      - ADMINER_SERVER=postgres
      - ADMINER_USERNAME=postgres
      - ADMINER_PASSWORD=postgres
      - ADMINER_DB=postgres
    ports:
      - 8080:8080
    container_name: adminer
    links:
      - postgres



  postgres:
    image: 'postgres:14'
    restart: always
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  crispcms:
    build:
      context: .
      args:
        - CRISP_VERSION=nightly
    container_name: crispcms
    links:
      - postgres
      - mailhog
    ports:
      - 80:80
      - 81:81
    environment:
        - CRISP_THEME=crisptheme
        - VERBOSITY=3
        - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/postgres
        - TZ=Europe/Berlin
        - HOST=${HOST}
        - ROOT=${HOST}
        - PROTO=https
        - ENVIRONMENT=development
        - LANG=en_US.UTF-8
        - DEFAULT_LOCALE=en
        - REQUIRE_LICENSE=false
        - THEME_GIT_COMMIT=${THEME_GIT_COMMIT}
    volumes:
      - crisp:/data
      - ./plugin:/plugins/lostplaces
      - ./assets:/data/files/assets
      - ./.env:/var/www/crisp/.env

volumes:
  crisp:
  postgres:
  typesense: